# Generated by Django 3.1.4 on 2021-01-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_auto_20210102_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='image',
        ),
        migrations.AddField(
            model_name='upload',
            name='image2',
            field=models.ImageField(default='fail.jpg', upload_to='images2'),
        ),
    ]
